### ISSUE TITLE
error messages on order bank from bg-merge

### ISSUE THREAD

**Issue by yurigotra** [baltzell/coatjava-3#114]
With new convention on the order variable it can be assigned values higher than 1 during background merging. 
bg-merge produces the following errors:
----> error : detector descriptor order must be [1..4]

**Comment by baltzell** [comment]
is this still a problem?

**Comment by baltzell** [comment]
Yuri says the problem doesn't exist with recent coatjavas.  Maybe an incompatibility between background merging version and the particular coatjava version used.
