### ISSUE TITLE
realpath: command not found on mac

### ISSUE THREAD

**Issue by raffaelladevita** [baltzell/coatjava-3#118]
Got this error when running recon-util on a Mac with Monterey version 12.6.9. 

The error originates from ```env.sh```.

The solution was to install with home-brew ```coreutils```, as suggested by many posts on the web. The same posts report that ```realpath``` may or may not be available on Mac depending on the version of the operating system and that it is available by default (only) starting from MacOS 13 (Ventura).

Is there an alternative command that is less system-dependent?

**Comment by c-dilks** [comment]
We can likely drop the `realpath` from `env.sh`, since we never had this before #110.

**Comment by c-dilks** [comment]
Apparently `realpath` was added in macOS 13, but we should keep compatibility with older versions.
