### ISSUE TITLE
Schema changes/additions

### ISSUE THREAD

**Issue by raffaelladevita** [baltzell/coatjava-3#158]
- add TBSegment bank to dcalign schema to make it suited for DCHV studies too in addition to alignment and AI validation
- add schema for Level3 studies

**Comment by hauenst** [comment]
Hi Raffaella,
We would need to have TBSegments and TBSegmentTrajectory. Not sure if both are included. 
we could also think to add all TimebasedTrkg banks in the schema in case we would need to troubleshoot reconstructed data.

**Comment by raffaelladevita** [comment]
addressed by #226 and #159
