### ISSUE TITLE
CI tests have been broken for a week

### ISSUE THREAD

**Issue by baltzell** [baltzell/coatjava-3#168]
Looks like due to a change in (unfrozen?) gemc 5.5.  Required tests for pull requests in this repo should be against a good, frozen version of gemc.

**Comment by c-dilks** [comment]
The culprit: https://github.com/gemc/clas12Tags/issues/5

Our solution here in `coatjava` is to trigger pipelines using a recent stable version of `clas12Tags` (nightly validation pipelines will continue to test the latest upstream trunk branches)
