### ISSUE TITLE
ALERT is missing DetectorTypes

### ISSUE THREAD

**Issue by baltzell** [baltzell/coatjava-3#273]

**Comment by baltzell** [comment]
and DetectorId values are inconstent with available DetectorType values, are they supposed to be the same?

**Comment by whit2333** [comment]
@baltzell Do we just make up a number or what? 
For some context here is what you mean, right?
https://github.com/JeffersonLab/coatjava/blob/development/common-tools/clas-detector/src/main/java/org/jlab/detector/base/DetectorType.java#L31

**Comment by whit2333** [comment]
What is the relationship between the numbers in DetectorType and the "group"s found [here](https://github.com/JeffersonLab/coatjava/blob/90f57f19a8e89a24da1b0da5a7ccf9b97ea360b7/etc/bankdefs/hipo4/data.json#L492) or [here](https://github.com/JeffersonLab/coatjava/blob/90f57f19a8e89a24da1b0da5a7ccf9b97ea360b7/etc/bankdefs/hipo/DATA.json#L383)?

**Comment by baltzell** [comment]
No relationship there.  Each must be unique, I think that's the only critical requirement, and the rest is just convention probably worth maintaining.

Closed by #360 and/or #361.
