### ISSUE TITLE
Cannot find source code for bank puts

### ISSUE THREAD

**Issue by whit2333** [baltzell/coatjava-3#353]
Could someone kindly point me to the code for the [Bank's Put methods](https://github.com/JeffersonLab/coatjava/blob/cfb6448e53aae15c9120e713d2c5ccaea1bc84c0/common-tools/clas-detector/src/main/java/org/jlab/detector/decode/CLASDecoder4.java#L284-L288)?

**Comment by baltzell** [comment]
probably this:  https://github.com/jeffersonlab/jnp
