### ISSUE TITLE
`hadd` executable conflicts with ROOT's `hadd`

### ISSUE THREAD

**Issue by c-dilks** [baltzell/coatjava-3#76]
If `coatjava/bin` takes priority in a user's `$PATH`, that user will have difficulty using ROOT's `hadd`. We should change the name of the `bin/hadd` script to something unique and avoid conflict with ROOT tools.

Note: the string `hadd` is not found in any `coatjava` source code.

**Comment by baltzell** [comment]
yes, bad name, should be hipo-hadd or somethingOn Aug 4, 2023, at 15:28, Christopher Dilks ***@***.***> wrote:﻿
If coatjava/bin takes priority in a user's $PATH, that user will have difficulty using ROOT's hadd. We should change the name of the bin/hadd script to something unique and avoid conflict with ROOT tools.
Note: the string hadd is not found in any coatjava source code.
