### ISSUE TITLE
address build script warnings about missing (and unnecessary) external-dependency jars

### ISSUE THREAD

**Issue by raffaelladevita** [baltzell/coatjava-3#80]
In the move from the old to the new repository and related cleanup, some unnecessary jars were removed from the external-dependencies folder. The build script needs to be updated to account for that, see the relevant build-log lines below
...
cp: external-dependencies/JEventViewer-1.1.jar: No such file or directory
cp: external-dependencies/vecmath-1.3.1-2.jar: No such file or directory

**Comment by baltzell** [comment]
Yes, they were intentionally removed.  And I saw the corresponding error messages from the script and ignored them, hoping we'd be moving to a more proper build system before long anyway ...
